### ISSUE TITLE
pub get doesn't work with dazel 0.3.1

### ISSUE THREAD

**Issue by Kleak** [dart-lang/bazel#138]
I have add this dev_dependencies and when i do pub get i got an error

```yaml
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  dazel: 0.3.1
```

The error :
```
Package _bazel_codegen has no versions that match >=0.0.2 <0.1.0 derived from:
  - dazel 0.3.1 depends on version ^0.0.2
```
